#include <omp.h>
#include <map>
#include <deque>
#include <string>
#include <string.h>
#include <vector>
#include <queue>
#include <algorithm>

#include <getopt.h>
#include <stdint.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <err.h>
#include <unistd.h>
using std::atoi; 
using std::min;
using std::max;
using std::endl;
using std::cerr;
using std::cout;
using std::deque; 
using std::queue;
using std::vector;
using std::map;
using std::ifstream;
using std::ofstream;
using std::string;
